### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by SolituderAlex** [wangtianrui/DCCRN#11]
Traceback (most recent call last):
  File "train.py", line 19, in <module>
    my_system = MyBaseSystem("./conf.yml")
  File "/root/DCCRN-master/BaseModel.py", line 38, in __init__
    data_home=conf["preset"]["data_home"]
  File "/root/DCCRN-master/BaseModel.py", line 106, in get_dns_data_loader
    val_set = DNSDataset(val_json_file, data_home=data_home)
  File "/root/DCCRN-master/dns_loader.py", line 21, in __init__
    self.mix_infos = json.load(f)
  File "/root/anaconda3/envs/DCCRN/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/root/anaconda3/envs/DCCRN/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/root/anaconda3/envs/DCCRN/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/root/anaconda3/envs/DCCRN/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by wangtianrui** [comment]
The JSON file may be faulty. Check the file and encoding mode which need to be the same as when they were generated.
